### ISSUE TITLE
Plugin configuration issue

### ISSUE THREAD

**Issue by ashwinvis** [pelican-plugins/webring#5]
I installed it following the readme. Some configuration steps are missing such as adding the to `PLUGINS` variable, which I guessed. I cannot build my website. What could be wrong?

```sh
www ❯ pip install pelican-webring    
Collecting pelican-webring
  Using cached https://files.pythonhosted.org/packages/97/af/04159f52d1ce2ca85eeec8f6a03344f13e2a89a5735119e9643ac459de86/pelican_webring-1.0.0-py3-none-any.whl
Collecting pelican<5.0,>=4.2 (from pelican-webring)
  Using cached https://files.pythonhosted.org/packages/73/fe/5c0413017438c77cb28a35ff5fe63887d913e32f39212502d49a7c32611b/pelican-4.2.0-py2.py3-none-any.whl
Collecting feedparser<6.0,>=5.2 (from pelican-webring)
  Using cached https://files.pythonhosted.org/packages/91/d8/7d37fec71ff7c9dbcdd80d2b48bcdd86d6af502156fc93846fb0102cb2c4/feedparser-5.2.1.tar.bz2
Requirement already satisfied: six>=1.4 in /home/avmo/.pyenv/versions/3.8.1/envs/www/lib/python3.8/site-packages (from pelican<5.0,>=4.2->pelican-webring) (1.14.0)
Requirement already satisfied: pytz>=0a in /home/avmo/.pyenv/versions/3.8.1/envs/www/lib/python3.8/site-packages (from pelican<5.0,>=4.2->pelican-webring) (2019.3)
Requirement already satisfied: python-dateutil in /home/avmo/.pyenv/versions/3.8.1/envs/www/lib/python3.8/site-packages (from pelican<5.0,>=4.2->pelican-webring) (2.6.0)
Requirement already satisfied: jinja2>=2.7 in /home/avmo/.pyenv/versions/3.8.1/envs/www/lib/python3.8/site-packages (from pelican<5.0,>=4.2->pelican-webring) (2.11.1)
Requirement already satisfied: feedgenerator>=1.9 in /home/avmo/.pyenv/versions/3.8.1/envs/www/lib/python3.8/site-packages (from pelican<5.0,>=4.2->pelican-webring) (1.9.1)
Requirement already satisfied: unidecode in /home/avmo/.pyenv/versions/3.8.1/envs/www/lib/python3.8/site-packages (from pelican<5.0,>=4.2->pelican-webring) (1.1.1)
Requirement already satisfied: docutils in /home/avmo/.pyenv/versions/3.8.1/envs/www/lib/python3.8/site-packages (from pelican<5.0,>=4.2->pelican-webring) (0.16)
Requirement already satisfied: pygments in /home/avmo/.pyenv/versions/3.8.1/envs/www/lib/python3.8/site-packages (from pelican<5.0,>=4.2->pelican-webring) (2.5.2)
Requirement already satisfied: blinker in /home/avmo/.pyenv/versions/3.8.1/envs/www/lib/python3.8/site-packages (from pelican<5.0,>=4.2->pelican-webring) (1.4)
Requirement already satisfied: MarkupSafe>=0.23 in /home/avmo/.pyenv/versions/3.8.1/envs/www/lib/python3.8/site-packages (from jinja2>=2.7->pelican<5.0,>=4.2->pelican-webring) (1.1.1)
Installing collected packages: pelican, feedparser, pelican-webring
  Found existing installation: pelican 4.0.1
    Uninstalling pelican-4.0.1:
      Successfully uninstalled pelican-4.0.1
  Found existing installation: feedparser 6.0.0b3
    Uninstalling feedparser-6.0.0b3:
      Successfully uninstalled feedparser-6.0.0b3
  Running setup.py install for feedparser ... done
Successfully installed feedparser-5.2.1 pelican-4.2.0 pelican-webring-1.0.0
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

~/www/ashwinvis.github.io enh/webring-mcss-update* 6s
www ❯ pip show pelican-webring   
Name: pelican-webring
Version: 1.0.0
Summary: Adds a webring to your site from a list of web feeds
Home-page: https://github.com/pelican-plugins/webring
Author: David Alfonso
Author-email: developer@davidalfonso.es
License: AGPL-3.0
Location: /home/avmo/.pyenv/versions/3.8.1/envs/www/lib/python3.8/site-packages
Requires: feedparser, pelican
Required-by: 

www ❯ DEBUG=1 make html                                                                                                                                                   
pelican /home/avmo/www/ashwinvis.github.io/content -o /home/avmo/www/ashwinvis.github.io/output -s /home/avmo/www/ashwinvis.github.io/pelicanconf.py -D
DEBUG: Pelican version: 4.2.0
DEBUG: Python version: 3.8.1
DEBUG: Add feed: Arch Linux
DEBUG: Add feed: Planet GNOME
DEBUG: Add feed: Planet KDE
['https://www.archlinux.org/feeds/planet/', 'http://planet.gnome.org/atom.xml', 'http://planet.kde.org/global/atom.xml']
DEBUG: Temporarily adding PLUGIN_PATHS to system path
DEBUG: Loading plugin `m.htmlsanity`
DEBUG: Registering plugin `m.htmlsanity`
DEBUG: Loading plugin `m.components`
DEBUG: Registering plugin `m.components`
DEBUG: Loading plugin `m.code`
DEBUG: Registering plugin `m.code`
DEBUG: Loading plugin `m.metadata`
DEBUG: Registering plugin `m.metadata`
DEBUG: Loading plugin `ipynb.markup`
DEBUG: Registering plugin `ipynb.markup`
DEBUG: Loading plugin `webring`
DEBUG: Registering plugin `webring`
CRITICAL: AttributeError: module 'webring' has no attribute 'register'
Traceback (most recent call last):
  File "/home/avmo/.pyenv/versions/www/bin/pelican", line 10, in <module>
    sys.exit(main())
  File "/home/avmo/.pyenv/versions/3.8.1/envs/www/lib/python3.8/site-packages/pelican/__init__.py", line 512, in main
    pelican, settings = get_instance(args)
  File "/home/avmo/.pyenv/versions/3.8.1/envs/www/lib/python3.8/site-packages/pelican/__init__.py", line 405, in get_instance
    return cls(settings), settings
  File "/home/avmo/.pyenv/versions/3.8.1/envs/www/lib/python3.8/site-packages/pelican/__init__.py", line 63, in __init__
    self.init_plugins()
  File "/home/avmo/.pyenv/versions/3.8.1/envs/www/lib/python3.8/site-packages/pelican/__init__.py", line 90, in init_plugins
    plugin.register()
AttributeError: module 'webring' has no attribute 'register'
make: *** [Makefile:54: html] Error 1
```

See also https://github.com/ashwinvis/ashwinvis.github.io/pull/23/files

**Comment by justinmayer** [comment]
Hi Ashwin. This is a (hopefully brief) period of transition for Pelican plugins, so your confusion is understandable. All of the plugins under this new [Pelican Plugins](https://github.com/pelican-plugins) organization have been converted to the new namespace plugin format that is meant for the next Pelican release. These plugins work just fine with Pelican <= 4.2 but not via the current README's instructions, which are written for Pelican current master. In the next Pelican release, plugins can be easily Pip-installed without having to make any settings file changes.

> Some configuration steps are missing such as adding the to PLUGINS variable

As noted above, those steps are not missing — they are simply not necessary for the next Pelican release that is in current master. Assuming you have cloned the Pelican repo to `~/projects/pelican/`, running the following in a fresh virtual environment should work just fine:

    pip install -e ~/projects/pelican
    pip install pelican-webring

All of this is documented very poorly at the moment, which we hope to improve in the lead-up to the next Pelican release. Please let me know if I can be of further assistance.

**Comment by ashwinvis** [comment]
Thank you for the detailed explanation. It seems like an improvement to me :rocket: 

> In the next Pelican release, plugins can be easily Pip-installed without having to make any settings file changes.

Can be / should be? Will legacy plugins which are not pip-installed be backwards compatible?

**Comment by justinmayer** [comment]
Can be. The previous method of handling plugins is fully supported, so there shouldn't be any backwards-incompatibilities. More info in (current master version of) the documentation: https://docs.getpelican.com/en/latest/plugins.html

**Comment by ashwinvis** [comment]
The plugin passes as a imported module. I leave this issue open until everything is documented.

**Comment by davidag** [comment]
Pelican 4.5 has been released and the new mechanism is detailed in the docs referenced by Justin here https://github.com/pelican-plugins/webring/issues/5#issuecomment-618356995
